name: Android CI

on:
  push:
    branches:
    - acv
    paths:
    - lib/workflows/android.dart


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v2
      with:
          distribution: 'zulu'
          java-version: 11

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.5'

    - run: flutter pub get

    - run: flutter build apk

    - name: Upload to Pgyer
      run: find ${{ github.workspace }}/build/app/outputs/flutter-apk/ -name "*.apk*" -type f -exec curl -F "file=@{}" -F "_api_key=${{ secrets.API_KEY }}" https://upload.pgyer.com/apiv1/app/upload  \;
